(
    SELECT CITY, LENGTH(CITY) 
    FROM (SELECT CITY FROM STATION ORDER BY LENGTH(CITY), CITY)
    WHERE ROWNUM = 1
)
UNION ALL
(
    SELECT CITY, LENGTH(CITY) 
    FROM (SELECT CITY FROM STATION ORDER BY LENGTH(CITY) DESC, CITY) 
    WHERE ROWNUM = 1
);
